name: C/C++ CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: make
      run: make

    - name: out
      uses: actions/upload-artifact@v2
      with:
        name: out
        path: ./
